name: SmartObscurer
favicon: null
layout_spectrum: 0.66774
typography_spectrum: 0.61948
title: Smart Obscurer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#898989'
    - '#f8f8f8'
    - '#5b5b5b'
    - '#cccccc'
    - '#222222'
  brandStrength: 0.8211953239515424
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.2426863128785044
purpose: []
